apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^inicio/', views.IndexTemplateView.as_view(), name='index'),
    url(r'^login/', views.log_in, name='log_in'),
    url(r'^registro-cliente/',
        views.crear_usuario,
        kwargs={'user': 'cliente'},
        name='crear_cliente'),
    url(r'^registro-proveedor/',
        views.crear_usuario,
        kwargs={'user': 'proveedor'},
        name='crear_proveedor'),
    url(r'^registro-persona/',
        views.crear_usuario,
        kwargs={'user': 'persona'},
        name='crear_persona'),
]

apps/proveedores/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^crear-producto/',
        views.ProductoProveedorCreateView.as_view(),
        name='crear_producto'),

    url(r'^modificar-producto/(?P<pk>\d+)/',
        views.ProductoProveedorUpdateView.as_view(),
        name='modificar_producto'),

    url(r'^lista-productos/',
        views.ProductoProveedorListView.as_view(),
        name='lista_productos'),

    url(r'^productos/',
        views.ProductoListView.as_view(),
        name='lista_productos_all'),

    url(r'^proveedor/(?P<pk>\d+)/',
        views.ProveedorDetailView.as_view(),
        name='proveedor'),

    url(r'^proveedores/',
        views.ProveedorListView.as_view(),
        name='proveedores'),
]

apps/ventas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^detalle-pedido/(?P<pk>\d+)/',
        views.PedidoDetailView.as_view(),
        name='detalle_pedido'),

    url(r'^pedidos/',
        views.PedidoProveedorListView.as_view(),
        kwargs={'filter': None},
        name='todos_los_pedidos'),

    url(r'^pedidos-enviados/',
        views.PedidoProveedorListView.as_view(),
        kwargs={'filter': 'enviados'},
        name='pedidos_enviados'),

    url(r'^pedidos-recibidos/',
        views.PedidoProveedorListView.as_view(),
        kwargs={'filter': 'recibidos'},
        name='pedidos_recibidos'),

    url(r'^pedidos-cliente/',
        views.PedidoClienteListView.as_view(),
        kwargs={'filter': None},
        name='todos_los_pedidos_cliente'),

    url(r'^pedidos-cliente-enviados/',
        views.PedidoClienteListView.as_view(),
        kwargs={'filter': 'enviados'},
        name='pedidos_enviados_cliente'),

    url(r'^pedidos-cliente-recibidos/',
        views.PedidoClienteListView.as_view(),
        kwargs={'filter': 'recibidos'},
        name='pedidos_recibidos_cliente'),

    url(r'^set-enviado/(?P<pk>\d+)/',
        views.SetPedidoView.as_view(),
        kwargs={'filter': 'enviado'},
        name='marcar_enviado'),

    url(r'^set-recibido/(?P<pk>\d+)/',
        views.SetPedidoView.as_view(),
        kwargs={'filter': 'recibido'},
        name='marcar_recibido'),

    url(r'^lista-servicios-cliente/',
        views.PedidoServicioClienteListView.as_view(),
        name='pedidos_servicio_cliente'),

    url(r'^lista-servicios-persona/',
        views.PedidoServicioPersonaListView.as_view(),
        name='pedidos_servicio_persona'),

    url(r'^pedido-servicio/(?P<pk>\d+)/',
        views.PedidoServicioDetailView.as_view(),
        name='detalle_pedido_servicio'),

    url(r'^iniciar-servicio/(?P<pk>\d+)/',
        views.StartPedidoView.as_view(),
        name='iniciar_servicio'),

    url(r'^terminar-servicio/(?P<pk>\d+)/',
        views.StopPedidoView.as_view(),
        name='terminar_servicio'),
]

construcosta2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.CountTemplateView.as_view(), name='count'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),
    url(r'^pagos/', include('apps.pagos.urls', namespace='pagos')),
    url(r'^proveedores/', include('apps.proveedores.urls', namespace='proveedores')),
    url(r'^servicios/', include('apps.servicios.urls', namespace='servicios')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/models.py
from django.db import models

# Create your models here.

apps/main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login as auth_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import TemplateView

from apps.clientes.forms import ClienteForm
from apps.proveedores.forms import ProveedorForm
from apps.servicios.forms import PersonaForm


def log_in(request):
    context= {}
    context['error'] = False
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                if user.is_staff or user.is_superuser:
                    return redirect('admin:index')
                else:
                    return redirect('main:index')
            else:
                context['msj'] = 'El usuario ha sido desactivado'
                context['error'] = True
        else:
            context['msj'] = 'usuario o contraseña incorrecta'
            context['error'] = True
    context['form_cliente'] = ClienteForm()
    context['form_proveedor'] = ProveedorForm()
    context['form_persona'] = PersonaForm()
    return render(request, 'login.html', context)


@login_required
def salir(request):
    logout(request)
    return redirect('main:log_in')


class IndexTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'apps/main/start.html'


class CountTemplateView(TemplateView):
    template_name = 'apps/main/index.html'


def crear_usuario(request, **kwargs):
    template_name = 'form_registro.html'
    form = None
    if kwargs['user'] is 'cliente':
        form = ClienteForm
    elif kwargs['user'] is 'proveedor':
        form = ProveedorForm
    elif kwargs['user'] is 'persona':
        form = PersonaForm
    form_class = form(request.POST or None)
    if request.POST and form_class.is_valid():
        form_class.save()
        return redirect('main:log_in')
    return render(request, template_name, {'form': form_class})

templates/apps/main/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bienvenido a construcosta</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap and Font Awesome css-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!-- Google fonts-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,700">
    <!-- Theme stylesheet-->
    <link rel="stylesheet" href="{% static 'assets_count/css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
      <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'assets_count/css/custom.css' %}">
    <!-- Favicon-->

  </head>
  <body>
    <div style="background-image: url('{% static 'assets_count/img/beach.jpg' %}')" class="main">
      <div class="overlay"></div>
      <div class="container">
        <p class="social">
            <a href="https://www.facebook.com/construcostabaq/" title="" class="facebook" target="_blank">
                <i class="fa fa-facebook"></i>
            </a>
            <a href="https://twitter.com/Construcostabaq" title="" class="twitter" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            <a href="https://www.instagram.com/construcostabaq/" title="" class="instagram" target="_blank">
                <i class="fa fa-instagram"></i>
            </a>
            <a href="{% url 'main:log_in' %}" title="" class="gplus">
                <i class="fa fa-sign-in"></i>
            </a>
        </p>
        <div class="row">
          <div class="col-sm-12">
            <h1 class="cursive">Construcosta</h1>
              <h3 class="sub">gran lanzamiento en:</h3>
          </div>
        </div>
        <!-- countdown-->
        <div id="countdown" class="countdown">
          <div class="row">
            <div class="countdown-item col-sm-3 col-xs-6">
              <div id="countdown-days" class="countdown-number">&nbsp;</div>
              <div class="countdown-label">dias</div>
            </div>
            <div class="countdown-item col-sm-3 col-xs-6">
              <div id="countdown-hours" class="countdown-number">&nbsp;</div>
              <div class="countdown-label">horas</div>
            </div>
            <div class="countdown-item col-sm-3 col-xs-6">
              <div id="countdown-minutes" class="countdown-number">&nbsp;</div>
              <div class="countdown-label">minutos</div>
            </div>
            <div class="countdown-item col-sm-3 col-xs-6">
              <div id="countdown-seconds" class="countdown-number">&nbsp;</div>
              <div class="countdown-label">segundos</div>
            </div>
          </div>
        </div>
        <!-- /.countdown-->
      </div>
    </div>
    <!-- JAVASCRIPT FILES -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'assets_count/js/jquery.cookie.js' %}"></script>
    <script src="{% static 'assets_count/js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'assets_count/js/front.js' %}"></script>

  </body>
</html>

templates/apps/main/start.html
{% extends 'base.html' %}

{% block title %}
    Bienvenido al inicio de
    {% if user.empresa %}
        comprador
    {% elif user.proveedor %}
        proveedor
    {% endif %}
    <strong>{{ user.get_full_name }} ({{ user.username }})</strong>
{% endblock %}


{% block content_main %}
    {% if user.cliente %}
        {% include 'apps/main/start_cliente.html' %}
    {% elif user.proveedor %}
        {% include 'apps/main/start_proveedor.html' %}
    {% elif user.persona %}
        {% include 'apps/main/start_persona.html' %}
    {% endif %}
{% endblock %}

{% block scripts_js %}
    {% load staticfiles %}
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
{% endblock %}

templates/apps/main/start_cliente.html
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-edit font-dark"></i>
                        <span class="caption-subject font-dark bold uppercase">
                            disfruta de los accesos rapidos del area
                            <span class="font-blue-soft">
                                de clientes
                            </span>
                        </span>
                    </div>
                    <div class="actions">

                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                            <div class="dashboard-stat dashboard-stat green-jungle">
                                <div class="visual">
                                    <i class="fa fa-users"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> Proveedores</div>
                                    <div class="desc"> lista de proveedores</div>
                                </div>
                                <a class="more" href="{% url 'proveedores:proveedores' %}">
                                    ver lista de proveedores
                                    <i class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                            <div class="dashboard-stat dashboard-stat blue-steel">
                                <div class="visual">
                                    <i class="fa fa-star"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> Servicios</div>
                                    <div class="desc"> lista de servicios</div>
                                </div>
                                <a class="more" href="">
                                    ver lista de servicios
                                    <i class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                            <div class="dashboard-stat dashboard-stat blue-dark">
                                <div class="visual">
                                    <i class="fa fa-cubes"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> Productos</div>
                                    <div class="desc"> lista de productos</div>
                                </div>
                                <a class="more" href="{% url 'proveedores:lista_productos_all' %}"> ver lista de productos
                                    <i class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                            <div class="dashboard-stat dashboard-stat yellow-casablanca">
                                <div class="visual">
                                    <i class="fa fa-user"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> Trabajadores</div>
                                    <div class="desc"> lista de trabajadores</div>
                                </div>
                                <a class="more" href="">
                                    ver lista de trabajadores
                                    <i class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/apps/main/start_persona.html
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-edit font-dark"></i>
                        <span class="caption-subject font-dark bold uppercase">
                            disfruta de los accesos rapidos del area
                            <span class="font-blue-soft">
                                de trabajadores
                            </span>
                        </span>
                    </div>
                    <div class="actions">

                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 margin-bottom-10">
                            <div class="dashboard-stat dashboard-stat green-jungle">
                                <div class="visual">
                                    <i class="fa fa-users"></i>
                                </div>
                                <div class="details">
                                    <div class="number"> Servicios</div>
                                    <div class="desc"> lista de servicios</div>
                                </div>
                                <a class="more" href="{% url 'ventas:pedidos_servicio_persona' %}">
                                    ver mi lista de servicios
                                    <i class="m-icon-swapright m-icon-white"></i>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

templates/apps/main/start_proveedor.html
<div class="row">
    <div class="col-md-12">
        <div class="portlet light ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-edit font-dark"></i>
                    <span class="caption-subject font-dark bold uppercase">
                            Bienvenido al inicio de proveedor
                            <span class="font-blue-soft">
                                {{ user.get_full_name }} ({{ user.username }})
                            </span>
                    </span>
                </div>
                <div class="actions">

                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <a class="dashboard-stat dashboard-stat-v2 green-haze" href="#">
                            <div class="visual">
                                <i class="fa fa-cube"></i>
                            </div>
                            <div class="details">
                                <div class="number">
                                        <span data-counter="counterup" data-value="{{ user.proveedor.get_productos.count }}">
                                            {{ user.proveedor.get_productos.count }}
                                        </span>
                                </div>
                                <div class="desc">
                                    <strong>Productos</strong>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <a class="dashboard-stat dashboard-stat-v2 purple-intense" href="#">
                            <div class="visual">
                                <i class="fa fa-star"></i>
                            </div>
                            <div class="details">
                                <div class="number">
                                        <span data-counter="counterup" data-value="{{ user.proveedor.get_historial_pedidos.count }}">
                                            {{ user.proveedor.get_historial_pedidos.count }}
                                        </span>
                                </div>
                                <div class="desc">
                                    <strong>Todos los pedidos</strong>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <a class="dashboard-stat dashboard-stat-v2 blue-sharp" href="#">
                            <div class="visual">
                                <i class="fa fa-file-text-o"></i>
                            </div>
                            <div class="details">
                                <div class="number">
                                        <span data-counter="counterup" data-value="{{ user.proveedor.get_pedidos_enviados.count }}">
                                            {{ user.proveedor.get_pedidos_enviados.count }}
                                        </span>
                                </div>
                                <div class="desc">
                                    <strong>Pedidos enviados</strong>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <a class="dashboard-stat dashboard-stat-v2 red-pink" href="#">
                            <div class="visual">
                                <i class="fa fa-user"></i>
                            </div>
                            <div class="details">
                                <div class="number">
                                        <span data-counter="counterup" data-value=" {{ user.proveedor.get_pedidos_recibidos.count }}">
                                             {{ user.proveedor.get_pedidos_recibidos.count }}
                                        </span>
                                </div>
                                <div class="desc">
                                    <strong>Pedidos recibidos</strong>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-edit font-dark"></i>
                    <span class="caption-subject font-dark bold uppercase">
                            disfruta de los accesos rapidos
                        </span>
                </div>
                <div class="actions">

                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <div class="dashboard-stat dashboard-stat green-jungle">
                            <div class="visual">
                                <i class="fa fa-users"></i>
                            </div>
                            <div class="details">
                                <div class="number"> Productos</div>
                                <div class="desc"> lista de Productos</div>
                            </div>
                            <a class="more" href="">
                                ver lista de clientes
                                <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <div class="dashboard-stat dashboard-stat blue-steel">
                            <div class="visual">
                                <i class="fa fa-star"></i>
                            </div>
                            <div class="details">
                                <div class="number"> Productos</div>
                                <div class="desc"> crear producto</div>
                            </div>
                            <a class="more" href="">
                                crear producto
                                <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <div class="dashboard-stat dashboard-stat blue-dark">
                            <div class="visual">
                                <i class="fa fa-file-text-o"></i>
                            </div>
                            <div class="details">
                                <div class="number"> Pedidos</div>
                                <div class="desc"> todos los pedidos</div>
                            </div>
                            <a class="more" href=""> ver todos los pedidos
                                <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom-10">
                        <div class="dashboard-stat dashboard-stat yellow-casablanca">
                            <div class="visual">
                                <i class="fa fa-user"></i>
                            </div>
                            <div class="details">
                                <div class="number"> Funcionarios</div>
                                <div class="desc"> lista de funcionarios</div>
                            </div>
                            <a class="more" href="">
                                ver lista de funcionarios
                                <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>