apps/api/ventas/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^enviar-venta/', views.VentaApiView.as_view()),
    url(r'^enviar-pedido/', views.PedidoServicioApiView.as_view()),
    url(r'^calificar/', views.post),

]

apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^inicio/', views.IndexTemplateView.as_view(), name='index'),
    url(r'^login/', views.log_in, name='log_in'),
    url(r'^registro-cliente/',
        views.crear_usuario,
        kwargs={'user': 'cliente'},
        name='crear_cliente'),
    url(r'^registro-proveedor/',
        views.crear_usuario,
        kwargs={'user': 'proveedor'},
        name='crear_proveedor'),
    url(r'^registro-persona/',
        views.crear_usuario,
        kwargs={'user': 'persona'},
        name='crear_persona'),
]

apps/ventas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^detalle-pedido/(?P<pk>\d+)/',
        views.PedidoDetailView.as_view(),
        name='detalle_pedido'),

    url(r'^pedidos/',
        views.PedidoProveedorListView.as_view(),
        kwargs={'filter': None},
        name='todos_los_pedidos'),

    url(r'^pedidos-enviados/',
        views.PedidoProveedorListView.as_view(),
        kwargs={'filter': 'enviados'},
        name='pedidos_enviados'),

    url(r'^pedidos-recibidos/',
        views.PedidoProveedorListView.as_view(),
        kwargs={'filter': 'recibidos'},
        name='pedidos_recibidos'),

    url(r'^pedidos-cliente/',
        views.PedidoClienteListView.as_view(),
        kwargs={'filter': None},
        name='todos_los_pedidos_cliente'),

    url(r'^pedidos-cliente-enviados/',
        views.PedidoClienteListView.as_view(),
        kwargs={'filter': 'enviados'},
        name='pedidos_enviados_cliente'),

    url(r'^pedidos-cliente-recibidos/',
        views.PedidoClienteListView.as_view(),
        kwargs={'filter': 'recibidos'},
        name='pedidos_recibidos_cliente'),

    url(r'^set-enviado/(?P<pk>\d+)/',
        views.SetPedidoView.as_view(),
        kwargs={'filter': 'enviado'},
        name='marcar_enviado'),

    url(r'^set-recibido/(?P<pk>\d+)/',
        views.SetPedidoView.as_view(),
        kwargs={'filter': 'recibido'},
        name='marcar_recibido'),

    url(r'^lista-servicios-cliente/',
        views.PedidoServicioClienteListView.as_view(),
        name='pedidos_servicio_cliente'),

    url(r'^lista-servicios-persona/',
        views.PedidoServicioPersonaListView.as_view(),
        name='pedidos_servicio_persona'),

    url(r'^pedido-servicio/(?P<pk>\d+)/',
        views.PedidoServicioDetailView.as_view(),
        name='detalle_pedido_servicio'),

    url(r'^iniciar-servicio/(?P<pk>\d+)/',
        views.StartPedidoView.as_view(),
        name='iniciar_servicio'),

    url(r'^terminar-servicio/(?P<pk>\d+)/',
        views.StopPedidoView.as_view(),
        name='terminar_servicio'),
]

construcosta2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.CountTemplateView.as_view(), name='count'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),
    url(r'^pagos/', include('apps.pagos.urls', namespace='pagos')),
    url(r'^proveedores/', include('apps.proveedores.urls', namespace='proveedores')),
    url(r'^servicios/', include('apps.servicios.urls', namespace='servicios')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/ventas/models.py
from django.db import models
from django.core import urlresolvers
# Create your models here.


class PedidoCliente(models.Model):
    proveedor = models.ForeignKey('proveedores.Proveedor')
    cliente = models.ForeignKey('clientes.Cliente')
    enviado = models.BooleanField(default=False, editable=False)
    recibido = models.BooleanField(default=False, editable=False)
    nota = models.TextField(blank=True, null=True)
    hora = models.TimeField(auto_now_add=True)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return 'pedido #{} creado {} , a las {}'.format(self.id, self.fecha, self.hora)

    def get_absolute_url(self):
        return urlresolvers.reverse_lazy('ventas:detalle_pedido',
                                         kwargs={
                                             'pk': self.pk
                                         })

    def set_to_enviado(self):
        return urlresolvers.reverse_lazy('ventas:marcar_enviado',
                                         kwargs={
                                             'pk': self.pk
                                         })

    def set_to_recibido(self):
        return urlresolvers.reverse_lazy('ventas:marcar_recibido',
                                         kwargs={
                                             'pk': self.pk
                                         })

    def get_total(self):
        total = 0
        for item in PedidoProductoItem.objects.filter(pedido=self):
            total += item.valor
        return total

    def get_estado(self):
        estado = 'sin revisar'
        if self.recibido:
            estado = 'recibido'
        elif self.enviado:
            estado = 'enviado'
        return estado


class PedidoProductoItem(models.Model):
    pedido = models.ForeignKey(PedidoCliente, related_name='pedido_item')
    producto = models.ForeignKey('proveedores.ProductoProveedor')
    cantidad = models.PositiveIntegerField()
    valor = models.PositiveIntegerField(editable=False)

    def save(self, *args, **kwargs):
        self.valor = self.producto.valor * self.cantidad
        super().save(*args, **kwargs)


class PedidoServicio(models.Model):
    cliente = models.ForeignKey('clientes.Cliente')
    persona = models.ForeignKey('servicios.Persona')
    horas_servicio = models.PositiveIntegerField()
    total = models.PositiveIntegerField(editable=False)
    nota = models.TextField(blank=True, null=True)
    fecha = models.DateField()
    hora = models.TimeField()
    fecha_solicitud = models.DateField(auto_now_add=True)
    calificacion = models.PositiveIntegerField(default=0, editable=False)
    iniciado = models.BooleanField(default=False, editable=False)
    terminado = models.BooleanField(default=False, editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.total = self.persona.valor_hora * self.horas_servicio
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return urlresolvers.reverse_lazy('ventas:detalle_pedido_servicio',
                                         kwargs={
                                             'pk': self.pk
                                         })

    def get_start_service_url(self):
        return urlresolvers.reverse_lazy('ventas:iniciar_servicio',
                                         kwargs={
                                             'pk': self.pk
                                         })

    def get_stop_service_url(self):
        return urlresolvers.reverse_lazy('ventas:terminar_servicio',
                                         kwargs={
                                             'pk': self.pk
                                         })

    def get_rank_service_url(self):
        return urlresolvers.reverse_lazy('ventas:calificar_servicio',
                                             kwargs={
                                                 'pk': self.pk
                                             })

apps/api/ventas/views.py
import json

from django.http import Http404
from django.http import HttpResponse
from rest_framework import generics
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import mixins
from rest_framework import generics

from apps.api.ventas.serializers import PedidoServicioSerializer, PedidoServicioRankSerializer
from apps.utils.print_colors import _green, _blue, _orange
from apps.ventas.models import PedidoCliente, PedidoProductoItem, PedidoServicio


class VentaApiView(APIView):
    def post(self, request, format=None):
        proveedor_id = request.data['proveedor_id']
        cliente_id = request.data['cliente_id']
        print(_green(request.data))
        data = request.data.copy()
        if proveedor_id and cliente_id:
            venta = PedidoCliente.objects.create(proveedor_id=int(proveedor_id),
                                                 cliente_id=int(cliente_id))
            dictlist = []
            data.pop('cliente_id', None)
            data.pop('proveedor_id', None)
            for key, value in data.items():
                temp = [key, value]
                dictlist.append(temp)

            dictlist.sort()
            for el in dictlist:
                print(_blue(el))

            l = len(dictlist)

            for index, obj in enumerate(dictlist):
                if index < (l - 1):
                    if index == 0 or index % 2 == 0:
                        cantidad = dictlist[index][1]
                        id = dictlist[index + 1][1]
                        print('id : {1} , cantidad : {0}'.format(cantidad, id))
                        producto = PedidoProductoItem()
                        producto.pedido = venta
                        producto.producto_id = int(id)
                        producto.cantidad = int(cantidad)
                        producto.save()
                        print('creado : id : {1} , cantidad : {0}'.format(cantidad, id))
            return Response({
                'valor_venta': venta.get_total()
            }, status=status.HTTP_201_CREATED)
        else:
            print('nope')
        return Response(request.data, status=status.HTTP_201_CREATED)


class PedidoServicioApiView(APIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = PedidoServicioSerializer

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            total = serializer.data['total']
            return Response({
                'total': total
            }, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def post(request):
    import json
    if request.POST:
        id = request.POST.get('id')
        calificacion = request.POST.get('calificacion')
        pedido = PedidoServicio.objects.get(id=int(id))
        print(calificacion)
        pedido.calificacion = calificacion
        pedido.save()
        return HttpResponse(
            json.dumps({'exito': 'pedido modificado'}),
            content_type="application/json"
        )

apps/ventas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.core import urlresolvers
# Create your views here.
from django.views.generic import DetailView
from django.views.generic import RedirectView

from apps.utils.views import BaseListViewDinamicHeader
from apps.ventas.models import PedidoCliente, PedidoProductoItem, PedidoServicio


class PedidoListViewMixin(BaseListViewDinamicHeader):
    model = PedidoCliente
    template_name = 'apps/ventas/lista_pedidos_cliente.html'


class PedidoClienteListView(PedidoListViewMixin):
    HEADER = ('proveedor', 'estado', 'fecha', 'valor')

    def get_queryset(self):
        filter = self.kwargs['filter']
        cliente = self.request.user.cliente
        kwargs = {'cliente': cliente}
        if filter is None:
            pass
        elif filter is 'enviados':
            kwargs['enviado'] = True
        elif filter is 'recibidos':
            kwargs['recibido'] = True
        return self.model.objects.filter(**kwargs).order_by('-fecha', '-hora')


class PedidoProveedorListView(PedidoListViewMixin):
    HEADER = ('cliente', 'estado', 'fecha', 'valor')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filtro'] = self.kwargs['filter']
        return context

    def get_queryset(self):
        filter = self.kwargs['filter']
        proveedor = self.request.user.proveedor
        kwargs = {'proveedor': proveedor}
        if filter is None:
            pass
        elif filter is 'enviados':
            kwargs['enviado'] = True
        elif filter is 'recibidos':
            kwargs['recibido'] = True
        return self.model.objects.filter(**kwargs).order_by('-fecha', '-hora')


class PedidoDetailView(LoginRequiredMixin, DetailView):
    model = PedidoCliente
    template_name = 'apps/ventas/detalle_pedido.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        productos = PedidoProductoItem.objects.filter(pedido_id=self.kwargs['pk'])
        print(productos)
        context['productos_pedido'] = productos
        return context


class SetPedidoView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        filter = self.kwargs['filter']
        pedido = PedidoCliente.objects.get(id=self.kwargs['pk'])
        if filter is 'enviado':
            pedido.enviado = True
        elif filter is 'recibido':
            pedido.recibido = True
        pedido.save()
        return urlresolvers.reverse_lazy('ventas:detalle_pedido',
                                         kwargs={
                                             'pk': self.kwargs['pk']
                                         })


class BasePedidoServicioListView(BaseListViewDinamicHeader):
    model = PedidoServicio
    template_name = 'apps/ventas/lista_pedidos_servicios_cliente.html'


class PedidoServicioClienteListView(BasePedidoServicioListView):
    HEADER = ('empleado', 'hora', 'fecha del servicio', 'fecha de solicitud', 'total')

    def get_queryset(self):
        return self.model.objects.filter(cliente=self.request.user.cliente)


class PedidoServicioPersonaListView(BasePedidoServicioListView):
    HEADER = ('cliente', 'persona', 'hora', 'fecha del servicio', 'fecha de solicitud')

    def get_queryset(self):
        return self.model.objects.filter(persona=self.request.user.persona)


class PedidoServicioDetailView(LoginRequiredMixin, DetailView):
    model = PedidoServicio
    template_name = 'apps/ventas/detalle_pedido_servicio.html'


class StartPedidoView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        pedido = PedidoServicio.objects.get(id=self.kwargs['pk'])
        pedido.iniciado = True
        pedido.save()
        return urlresolvers.reverse_lazy('ventas:detalle_pedido_servicio',
                                         kwargs={
                                             'pk': self.kwargs['pk']
                                         })


class StopPedidoView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        pedido = PedidoServicio.objects.get(id=self.kwargs['pk'])
        pedido.terminado = True
        pedido.iniciado = False
        pedido.save()
        return urlresolvers.reverse_lazy('ventas:detalle_pedido_servicio',
                                         kwargs={
                                             'pk': self.kwargs['pk']
                                         })

templates/apps/ventas/detalle_pedido.html
{% extends 'base.html' %}

{% load i18n staticfiles humanize %}

{% block title %}
    Pedido #{{ object.id }}
{% endblock %}


{% block content_main %}
    <div class="row">
        <div class="col-md-12" align="center">
            {% if user.cliente %}
                <a href="{% url 'ventas:todos_los_pedidos_cliente' %}" class="btn btn-lg green hidden-print margin-bottom-5">
                    Volver
                    <i class="fa fa-arrow-left"></i>
                </a>
            {% elif user.proveedor %}
                <a href="{% url 'ventas:todos_los_pedidos' %}" class="btn btn-lg green hidden-print margin-bottom-5">
                    Volver
                    <i class="fa fa-arrow-left"></i>
                </a>
            {% endif %}

            <a class="btn btn-lg blue hidden-print margin-bottom-5" onclick="javascript:window.print();">
                Imprimir
                <i class="fa fa-print"></i>
            </a>
            {% if user.proveedor %}
                {% if object.enviado %}
                    <a class="btn btn-lg purple-plum hidden-print margin-bottom-5">
                        Pedido Enviado
                        <i class="fa fa-check"></i>
                    </a>
                {% else %}
                    <a class="btn btn-lg green-jungle hidden-print margin-bottom-5" href="{{ object.set_to_enviado }}">
                        Marcar como enviado
                        <i class="fa fa-send"></i>
                    </a>
                {% endif %}
            {% endif %}
            {% if user.cliente and object.enviado %}
                {% if object.recibido %}
                    <a class="btn btn-lg purple-plum hidden-print margin-bottom-5">
                        Pedido Recibido
                        <i class="fa fa-check"></i>
                    </a>
                {% else %}
                    <a class="btn btn-lg green-jungle hidden-print margin-bottom-5" href="{{ object.set_to_recibido }}">
                        Marcar como recibido
                        <i class="fa fa-send"></i>
                    </a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-edit font-dark"></i>
                        <span class="caption-subject font-dark bold uppercase">
                            pedido # {{ object.id }}, estado actual : {{ object.get_estado }}
                        </span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="invoice">
                        <div class="row">
                            <div class="col-xs-6">
                                <h4>Datos del Cliente</h4>
                                <ul class="list-unstyled">
                                    <li>
                                        nombre:
                                        <strong>
                                            {{ object.cliente.get_full_name|upper }}
                                        </strong>
                                        <strong class="label label-info">
                                            {{ object.cliente.tipo }}
                                        </strong>
                                    </li>
                                    <li>
                                        direccion:
                                        <strong>
                                            {{ object.cliente.direccion }}
                                        </strong>
                                    </li>
                                    {% if object.cliente.nit %}
                                        <li>
                                            nit: <strong>{{ object.cliente.nit }}</strong>
                                        </li>
                                    {% endif %}
                                    {% if object.cliente.rut %}
                                        <li> rut: <strong>{{ object.cliente.rut }}</strong></li>
                                    {% endif %}
                                    <li>
                                        telefono: <strong>{{ object.cliente.telefono }}</strong>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-xs-6 text-right">
                                <h4>Informacion del proveedor:</h4>
                                <ul class="list-unstyled">
                                    <li>
                                        <strong>{{ object.proveedor }}</strong>
                                    </li>
                                    <li>
                                        Direccion: <br>
                                        <strong>{{ object.proveedor.direccion }}</strong>
                                    </li>
                                    <li>
                                        Telefono: <br>
                                        <strong>{{ object.proveedor.telefono }}</strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <table class="table table-striped table-hover table-bordered">
                                    <thead>
                                    <tr>
                                        <th class="text-center">Nombre del producto</th>
                                        <th class="text-center">Precio unitario</th>
                                        <th class="text-center">Cantidad</th>
                                        <th class="text-center">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for elemento in productos_pedido %}
                                        <tr>
                                            <td class="text-center">{{ elemento.producto }}</td>
                                            <td class="text-center">${{ elemento.producto.valor|intcomma }}</td>
                                            <td class="text-center">{{ elemento.cantidad }}</td>
                                            <td class="text-center">${{ elemento.valor|intcomma }}</td>
                                        </tr>
                                    {% endfor %}
                                    <tr>
                                        <td colspan="3" class="text-right">
                                            <strong>total</strong>
                                        </td>
                                        <td colspan="3" class="text-center">
                                            $<strong>{{ object.get_total|intcomma }}</strong>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/apps/ventas/lista_pedidos_cliente.html
{% extends 'utils/list_base.html' %}

{% block title %}Lista de pedidos{% endblock %}

{% block content_main_title %}Lista de pedidos{% endblock %}

{% block content_main_top_bar %}
    <a href="{% url 'main:index' %}" class="btn blue">
        <i class="fa fa-arrow-left"></i> Regresar al inicio <i class="fa fa-home"></i>
    </a>
{% endblock %}
{% block content_main_list_title %}
    Lista de pedidos {{ filtro }}
{% endblock %}
{% block content_main_table_data %}
    {% load humanize %}
    <tr class="">
        <td class="text-center">
            {% if user.proveedor %}
                {{ obj.cliente }}
            {% elif user.cliente %}
                <a href="{{ obj.proveedor.get_absolute_url }}">
                    {{ obj.proveedor }}
                </a>
            {% endif %}
        </td>
        <td class="text-center">{{ obj.get_estado }}</td>
        <td class="text-center">{{ obj.fecha }}</td>
        <td class="text-center">${{ obj.get_total|intcomma }}</td>
        <td class="text-center">
            <div class="tr-action">
                <div class="tr-action-inner">
                        <a href="{{ obj.get_absolute_url }}" class="btn btn-info btn-xs"
                           data-toggle="tooltip" data-placement="top" title="Ver">
                            <i class="fa fa-eye"></i>
                        </a>
                </div>
            </div>
        </td>
    </tr>
{% endblock %}

{% block main-else-msg %}Todavía no tienes pedidos <strong>{{ filtro }}</strong>.{% endblock %}

templates/apps/ventas/lista_pedidos_servicios_cliente.html
{% extends 'utils/list_base.html' %}

{% block title %}Lista de servicios solicitados{% endblock %}

{% block content_main_title %}Lista de servicios solicitados{% endblock %}

{% block content_main_top_bar %}
    <a href="{% url 'main:index' %}" class="btn blue">
        <i class="fa fa-arrow-left"></i> Regresar al inicio <i class="fa fa-home"></i>
    </a>
{% endblock %}
{% block content_main_list_title %}
    Lista de servicios solicitados
{% endblock %}
{% block content_main_table_data %}
    {% load humanize %}
    <tr class="">
        <td class="text-center">
            {% if user.persona %}
                {{ obj.cliente }}
            {% elif user.cliente %}
                <a href="{{ obj.proveedor.get_absolute_url }}">
                    {{ obj.persona.get_full_name }}
                </a>
            {% endif %}
        </td>
        <td class="text-center">{{ obj.hora }}</td>
        <td class="text-center">{{ obj.fecha }}</td>
        <td class="text-center">{{ obj.fecha_solicitud }}</td>
        <td class="text-center">${{ obj.total|intcomma }}</td>
        <td class="text-center">
            <div class="tr-action">
                <div class="tr-action-inner">
                        <a href="{{ obj.get_absolute_url }}" class="btn btn-info btn-xs"
                           data-toggle="tooltip" data-placement="top" title="Ver">
                            <i class="fa fa-eye"></i>
                        </a>
                </div>
            </div>
        </td>
    </tr>
{% endblock %}

{% block main-else-msg %}Todavía no tienes pedidos <strong>{{ filtro }}</strong>.{% endblock %}