apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^inicio/', views.IndexTemplateView.as_view(), name='index'),
    url(r'^login/', views.log_in, name='log_in'),
    url(r'^registro-cliente/',
        views.crear_usuario,
        kwargs={'user': 'cliente'},
        name='crear_cliente'),
    url(r'^registro-proveedor/',
        views.crear_usuario,
        kwargs={'user': 'proveedor'},
        name='crear_proveedor'),
    url(r'^registro-persona/',
        views.crear_usuario,
        kwargs={'user': 'persona'},
        name='crear_persona'),
]

construcosta2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.CountTemplateView.as_view(), name='count'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),
    url(r'^pagos/', include('apps.pagos.urls', namespace='pagos')),
    url(r'^proveedores/', include('apps.proveedores.urls', namespace='proveedores')),
    url(r'^servicios/', include('apps.servicios.urls', namespace='servicios')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <title>construcosta | {% block title %}{% endblock %}</title>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        {% load staticfiles %}
        <script src="{% static 'js/vendors/01-jquery.js' %}"></script>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.3.0/css/simple-line-icons.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        {% load staticfiles %}
        {% include 'statics/css/base.html' %}
        <link rel="stylesheet" href="{% static 'css/template/layout.css' %}">
        <link rel="stylesheet" href="{% static 'css/template/blue.css' %}">
        <link rel="stylesheet" href="{% static 'css/template/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
        <link href="{% static 'img/favicon.png' %}" rel="icon">

        {% block css_extra %}{% endblock %}

        {% include 'statics/js/js.html' %}

        {% block js_header %}{% endblock %}

    </head>
    <!-- END HEAD -->

    <body id="app" class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-sidebar-fixed page-md">
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner ">
                <!-- BEGIN LOGO -->
                <div class="page-logo">

                    <div class="menu-toggler sidebar-toggler">
                        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
                    </div>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>

                <!-- BEGIN PAGE TOP -->
                <div class="page-top">
                    <!-- BEGIN TOP NAVIGATION MENU -->
                    <div class="top-menu">
                        <ul class="nav navbar-nav pull-right">
                            {% include 'menu/user/usuario.html' %}
                        </ul>
                    </div>
                    <!-- END TOP NAVIGATION MENU -->
                </div>
                <!-- END PAGE TOP -->
            </div>
            <!-- END HEADER INNER -->
        </div>
        <!-- END HEADER -->
        <!-- BEGIN HEADER & CONTENT DIVIDER -->
        <div class="clearfix"> </div>
        <!-- END HEADER & CONTENT DIVIDER -->
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar-wrapper">
                <!-- END SIDEBAR -->
                <div class="page-sidebar navbar-collapse collapse">
                    <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                        {% include 'menu/sidebar/base.html' %}
                    </ul>
                    <!-- END SIDEBAR MENU -->
                </div>
                <!-- END SIDEBAR -->
            </div>
            <!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    {% block content_main %}{% endblock %}
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->

        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner"> 2016 &copy; ConstruCosta S.A.S 2016
                todos los derechos reservados
                <div class="scroll-to-top">
                    <i class="icon-arrow-up"></i>
                </div>
            </div>
        </div>

        {% block scripts_js %}
        {% endblock %}
        <script src="{% static 'js/sweetalert-dev.js' %}"></script>

    </body>
</html>

templates/form_registro.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>ConstruCosta | Registro</title>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
          type="text/css"/>
    <link rel="stylesheet"
          href="http://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    {% load staticfiles widget_tweaks %}
    {% include 'statics/css/base.html' %}
    <link rel="stylesheet" href="{% static 'css/template/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/template/select2-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/template/login-5.min.css' %}">
    <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
    {% include 'statics/js/js.html' %}
<link href="{% static 'img/favicon.png' %}" rel="icon">

<body class=" login" id="app">

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
           <h1> Registarse como {{ form.title }}</h1>
        </div>
        <form method="post">{% csrf_token %}
            {% for field in form %}
                <div class="col-md-12">
                    <div class="form-group form-md-line-input {% if field.errors %} has-error {% elif field.value %} has-success {% endif %}">
                        <label class="col-md-3 control-label">
                            {{ field.label }}
                        </label>
                        <div class="col-md-12">
                            {% render_field field class="form-control" %}
                            <span class="help-block">
                            {{ field.help_text }}
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                        </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-md-12">
                <div align="center">
                    <br>
                    <a type="submit" id="lock" href="javascript: history.go(-1)" data-loading-text="Cancelando..."
                       class="btn btn-danger">
                        Cancelar <i class="fa fa-close"></i>
                    </a>
                    <button class="btn green" type="submit">
                        Guardar <i class="fa fa-save"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>


</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>ConstruCosta | Login</title>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
          type="text/css"/>
    <link rel="stylesheet"
          href="http://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    {% load staticfiles widget_tweaks %}
    {% include 'statics/css/base.html' %}
    <link rel="stylesheet" href="{% static 'css/template/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/template/select2-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/template/login-5.min.css' %}">
    <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    {% include 'statics/js/js.html' %}

<body class=" login" id="app">

<div class="user-login-5">
    <div class="row bs-reset">
        <div class="col-md-6 bs-reset">
            {% load staticfiles %}
            <div class="login-bg"
                 style="background-image:url(http://www.cursosgratisde.com/wp-content/uploads/2016/06/construccion-sostenible.jpg)">
            </div>
        </div>
        <div class="col-md-6 login-container bs-reset" align="center">
            <img src="{% static 'img/logo.jpg' %}" alt="" width="45%">
            <div class="login-content" style="margin-top: -5%">
                <h1 class="text-center">ConstruCosta</h1>
                <h3 class="text-center">Bienvenidos</h3>
                <p class="text-center">
                    <strong style="color: #494949">
                        Area exclusiva
                    </strong>
                </p>
                <form class="login-form" method="post">{% csrf_token %}
                    {% if error %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                            <strong>Error</strong>, {{ msj }}
                        </div>
                    {% endif %}
                    <div class="alert alert-danger display-hide">
                        <button class="close" data-close="alert"></button>
                        <span>Escriba el nombre de usuario y la contraseña. </span>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <input class="form-control form-control-solid placeholder-no-fix form-group" type="text"
                                   autocomplete="off" placeholder="Usuario" name="username" required/></div>
                        <div class="col-xs-6">
                            <input class="form-control form-control-solid placeholder-no-fix form-group" type="password"
                                   autocomplete="off" placeholder="Clave" name="password" required/></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12" align="center">
                            <button class="btn green btn-md" type="submit">
                                iniciar sesion <i class="fa fa-sign-in"></i>
                            </button>
                            <a data-toggle="modal" href="#registro" class="btn yellow-crusta btn-md">
                                Registrarse <i class="fa fa-user-plus"></i>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
            <div class="login-footer">
                <div class="row bs-reset">
                    <div class="col-xs-5 bs-reset">
                        <ul class="login-social">
                            <li>
                                <a href="https://www.facebook.com/construcostabaq/" target="_blank">
                                    <i class="icon-social-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/Construcostabaq" target="_blank">
                                    <i class="icon-social-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/construcostabaq/" target="_blank">
                                    <i class="icon-social-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-xs-7 bs-reset">
                        <div class="login-copyright text-right">
                            <strong>Copyright &copy; ConstruCosta 2017</strong>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="registro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel" align="center">Que desea hacer en la plataforma?</h4>
            </div>
            <div class="modal-body" align="center">
                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'main:crear_cliente' %}" class="btn green-jungle btn-lg btn-form" id="cliente">
                            quiero comprar <i class="fa fa-dollar"></i>
                        </a>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'main:crear_proveedor' %}" class="btn yellow-crusta btn-lg btn-form" id="proveedor">
                            quiero vender <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'main:crear_persona' %}" class="btn purple btn-lg btn-form" id="persona">
                            quiero trabajar <i class="fa fa-briefcase" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>



</body>
</html>