apps/api/proveedores/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views, viewsets

router = routers.DefaultRouter()
router.register(r'categorias', viewsets.CategoriaProductoViewSet)
router.register(r'marcas', viewsets.MarcaViewSet)
router.register(r'productos-proveedor', viewsets.ProductoProveedorViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^productos/', views.ProductoProveedortList.as_view())
]

apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^inicio/', views.IndexTemplateView.as_view(), name='index'),
    url(r'^login/', views.log_in, name='log_in'),
    url(r'^registro-cliente/',
        views.crear_usuario,
        kwargs={'user': 'cliente'},
        name='crear_cliente'),
    url(r'^registro-proveedor/',
        views.crear_usuario,
        kwargs={'user': 'proveedor'},
        name='crear_proveedor'),
    url(r'^registro-persona/',
        views.crear_usuario,
        kwargs={'user': 'persona'},
        name='crear_persona'),
]

apps/proveedores/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^crear-producto/',
        views.ProductoProveedorCreateView.as_view(),
        name='crear_producto'),

    url(r'^modificar-producto/(?P<pk>\d+)/',
        views.ProductoProveedorUpdateView.as_view(),
        name='modificar_producto'),

    url(r'^lista-productos/',
        views.ProductoProveedorListView.as_view(),
        name='lista_productos'),

    url(r'^productos/',
        views.ProductoListView.as_view(),
        name='lista_productos_all'),

    url(r'^proveedor/(?P<pk>\d+)/',
        views.ProveedorDetailView.as_view(),
        name='proveedor'),

    url(r'^proveedores/',
        views.ProveedorListView.as_view(),
        name='proveedores'),
]

construcosta2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.CountTemplateView.as_view(), name='count'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),
    url(r'^pagos/', include('apps.pagos.urls', namespace='pagos')),
    url(r'^proveedores/', include('apps.proveedores.urls', namespace='proveedores')),
    url(r'^servicios/', include('apps.servicios.urls', namespace='servicios')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/proveedores/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core import urlresolvers
from django.contrib.humanize.templatetags.humanize import intcomma
# Create your models here.
from apps.servicios.models import BaseNombre
from apps.ventas.models import PedidoCliente


class Proveedor(User):
    nit = models.CharField(max_length=50, unique=True, blank=True, null=True)
    rut = models.CharField(max_length=50, unique=True, blank=True, null=True)
    imagen = models.URLField(blank=True, null=True)
    direccion = models.CharField(max_length=50)
    telefono = models.PositiveIntegerField()
    TIPOS = (
        ('EMPRESA', 'EMPRESA'),
        ('PERSONA INDEPENDIENTE', 'PERSONA INDEPENDIENTE')
    )
    tipo = models.CharField(max_length=50, choices=TIPOS)

    class Meta:
        verbose_name = 'Usuario Proveedor'
        verbose_name_plural = 'Usuarios Proveedores'

    def __str__(self):
        return self.get_full_name().upper()

    def get_absolute_url(self):
        return urlresolvers.reverse_lazy('proveedores:proveedor',
                                         kwargs={
                                             'pk': self.pk
                                         })

    def get_productos(self):
        return ProductoProveedor.objects.filter(proveedor=self)

    def get_historial_pedidos(self):
        return PedidoCliente.objects.filter(proveedor=self)

    def get_pedidos_enviados(self):
        return PedidoCliente.objects.filter(proveedor=self, enviado=True)

    def get_pedidos_recibidos(self):
        return PedidoCliente.objects.filter(proveedor=self, recibido=True)


class CategoriaProducto(BaseNombre):
    def productos(self):
        return ProductoProveedor.objects.filter(categoria_producto=self).count()


class Marca(BaseNombre):
    def productos(self):
        return ProductoProveedor.objects.filter(marca=self).count()


class ProductoProveedor(models.Model):
    nombre = models.CharField(max_length=50)
    categoria_producto = models.ForeignKey(CategoriaProducto)
    marca = models.ForeignKey(Marca)
    valor = models.PositiveIntegerField()
    proveedor = models.ForeignKey(Proveedor)
    imagen = models.URLField(default='https://http2.mlstatic.com/S_912711-MLA20615911030_032016-O.jpg')

    def __str__(self):
        return self.nombre

    def get_update_url(self):
        return urlresolvers.reverse_lazy('proveedores:modificar_producto',
                                         kwargs={
                                             'pk':self.pk
                                         })

apps/proveedores/forms.py
from apps.proveedores.models import Marca, CategoriaProducto
from apps.utils import forms
from . import models


class ProveedorForm(forms.BaseUserCreationForm):
    title = 'Proveedor'

    class Meta(forms.BaseUserCreationForm.Meta):
        model = models.Proveedor


class ProductoProveedorForm(forms.ProveedorObjectMixinForm,
                            forms.FormAllFields):

    title = 'Producto'

    class Meta(forms.FormAllFields.Meta):
        model = models.ProductoProveedor


class FiltroProductoForm(forms.forms.Form):
    nombre = forms.forms.CharField(max_length=200)
    marca = forms.forms.ModelChoiceField(
        queryset=Marca.objects.all()
    )
    categoria = forms.forms.ModelChoiceField(
        queryset=CategoriaProducto.objects.all()
    )

apps/api/proveedores/views.py
from rest_framework import generics
from rest_framework import mixins
from rest_framework import permissions
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.api.proveedores.serializers import ProductoProveedorSerializer
from apps.proveedores.models import ProductoProveedor


class BaseApiViewList(mixins.ListModelMixin, generics.GenericAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class ProductoProveedortList(BaseApiViewList):
    queryset = ProductoProveedor.objects.all()
    serializer_class = ProductoProveedorSerializer

apps/proveedores/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import BaseDetailView, DetailView

from apps.proveedores.forms import FiltroProductoForm
from apps.proveedores.models import ProductoProveedor, Proveedor
from django.core import urlresolvers
from . import models
from apps.utils.views import SetProveedorFormView, BaseCreateView, FilterProveedorUser, BaseListViewDinamicHeader, \
    BaseUpdateView, BaseListView
from . import forms
# Create your views here.


class ProveedorCreateViewMixin(SetProveedorFormView):
    form_class = forms.ProductoProveedorForm
    success_url = urlresolvers.reverse_lazy('proveedores:lista_productos')


class ProductoProveedorCreateView(ProveedorCreateViewMixin, BaseCreateView):
    pass


class ProductoProveedorUpdateView(ProveedorCreateViewMixin, BaseUpdateView):
    model = models.ProductoProveedor


class ProductoProveedorListView(FilterProveedorUser):
    model = ProductoProveedor
    HEADER = ('nombre', 'categoria', 'marca', 'valor')
    template_name = 'apps/proveedores/lista_productos.html'


class BaseReturnFrontendFilterForm(object):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FiltroProductoForm()
        return context


class ProductoListView(BaseReturnFrontendFilterForm, BaseListView):
    model = ProductoProveedor
    template_name = 'apps/proveedores/productos_all.html'


class ProveedorDetailView(LoginRequiredMixin, BaseReturnFrontendFilterForm, DetailView):
    model = Proveedor
    template_name = 'apps/proveedores/detalle_proveedor.html'


class ProveedorListView(LoginRequiredMixin, ListView):
    model = Proveedor
    template_name = 'apps/proveedores/lista_proveedores.html'

templates/apps/proveedores/detalle_proveedor.html
{% extends 'base.html' %}
{% load widget_tweaks staticfiles %}
{% block content_main %}

    <div id="content_">
        <div class="dom">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">

                    </div>
                    <div class="col-md-9">
                        <h4 class="text-center">aca puedes comprar productos, simplemente verlos</h4>
                    </div>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row profile">
                    <div class="col-md-3">
                        <div class="profile-sidebar">
                            <!-- SIDEBAR USERPIC -->
                            <div class="profile-userpic">
                                <img src="{{ object.imagen }}"
                                     class="img-responsive" alt="">
                            </div>
                            <!-- END SIDEBAR USERPIC -->
                            <!-- SIDEBAR USER TITLE -->
                            <div class="profile-usertitle">
                                <div class="profile-usertitle-name">
                                    {{ object.get_full_name }}
                                </div>
                                <div class="profile-usertitle-job">
                                    <strong>{{ object.tipo }}</strong>
                                </div>
                            </div>
                            <!-- END SIDEBAR USER TITLE -->
                            <!-- SIDEBAR BUTTONS -->
                            <div class="profile-userbuttons">
                                direccion: <strong>{{ object.direccion }}</strong>
                                <br>
                                telefono: <strong>{{ object.telefono }}</strong>
                            </div>
                            <!-- END SIDEBAR BUTTONS -->
                            <!-- SIDEBAR MENU -->
                            <div class="profile-usermenu">
                                <ul class="nav">
                                    <li class="active">
                                        <a href="#">
                                            <i class="fa fa-shopping-cart"></i>
                                            productos
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- END MENU -->
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="profile-content">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input class="form-control" id="id_nombre" maxlength="200"
                                               placeholder="escriba el nombre del producto" name="nombre" type="text"
                                               required="">
                                    </div>
                                </div>
                                <div class="col-md-6" align="center">
                                    <h1>
                                        total: $<strong id="total_ganancia">0</strong>
                                    </h1>
                                    <button class="btn btn-lg btn-success" id="finish">
                                        Guardar pedido
                                    </button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="list-group lista-productos">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <br>
                                    <div class="list-group productos_venta">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts_js %}
    <script type="text/template" id="productos_item">
        <a align="center" class="list-group-item">
            <div class="media">
                <div class="pull-left">
                    <img class="media-object producto-proveedor" src="<%= imagen %>" alt="Image">
                </div>
                <div class="media-body">
                    <h4 class="media-heading" id="name_<%= id %>"><%= nombre %></h4>
                    $<strong id="valor_<%= id %>"><%= valor %></strong>
                    <br>
                    categoria: <strong><%= categoria_nombre %></strong>
                    <br>
                    marca: <strong><%= marca_nombre %></strong>
                </div>
                <button class="btn btn-success btn-xs add" id="<%= id %>">
                    agregar <i class="fa fa-plus"></i>
                </button>
            </div>
        </a>
        <br>
    </script>

    <script type="text/template" id="productos_venta_item">
        <a align="center" class="list-group-item">
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading"><%= nombre %></h4>
                    cantidad: <strong><%= cantidad %></strong>
                </div>
                <button class="btn btn-danger btn-xs delete" id="<%= producto_id %>">
                    eliminar <i class="fa fa-trash"></i>
                </button>
            </div>
        </a>
        <br>
    </script>

    <script type="text/template" id="menu_after_success">

        <div class="row" align="center">
            <div class="col-md-6 text-left">
                <h2>
                    {% if venta %}
                        Venta Exitosa
                    {% else %}
                        Pedido Exitoso
                    {% endif %}
                    <i class="fa fa-check green-text"></i>
                </h2>
            </div>
            <div class="col-md-6 text-right">
                <h2>
                    Total Pedido : $<strong id="ganancia" class="green-text"></strong>
                </h2>
            </div>
        </div>

    </script>

    <script type="text/javascript">
        window.proveedor = {{ object.id }};
        window.cliente = {{ user.cliente.id }};
    </script>
    <script src="{% static 'js/counter.js' %}"></script>
    <script src="{% static 'js/underscore.js' %}"></script>
    <script src="{% static 'js/backbone.js' %}"></script>
    <script src="{% static 'js/backbone/proveedores/models.js' %}"></script>
    <script src="{% static 'js/backbone/proveedores/collections.js' %}"></script>
    <script src="{% static 'js/backbone/proveedores/ventaViews.js' %}"></script>
    <script src="{% static 'js/backbone/app.js' %}"></script>

{% endblock %}

templates/apps/proveedores/lista_productos.html
{% extends 'utils/list_base.html' %}

{% block title %}Tu lista de productos{% endblock %}

{% block content_main_title %}Tus Productos{% endblock %}

{% block content_main_top_bar %}
    <a href="{% url 'main:index' %}" class="btn blue">
        <i class="fa fa-arrow-left"></i> Regresar al inicio <i class="fa fa-home"></i>
    </a>
{% endblock %}
{% block content_main_list_title %}
    Lista de productos
{% endblock %}
{% block content_main_table_data %}
    {% load humanize %}
    <tr class="">
        <td class="text-center">{{ obj.nombre }}</td>
        <td class="text-center">{{ obj.categoria_producto }}</td>
        <td class="text-center">{{ obj.marca }}</td>
        <td class="text-center">${{ obj.valor|intcomma }}</td>
        <td class="text-center">
            <div class="tr-action">
                <div class="tr-action-inner">
                        <a href="{{ obj.get_update_url }}" class="btn btn-primary btn-xs"
                           data-toggle="tooltip" data-placement="top" title="Editar">
                            <i class="fa fa-pencil"></i>
                        </a>
                </div>
            </div>
        </td>
    </tr>
{% endblock %}

{% block main-else-msg %}Todavía no tienes productos creados.{% endblock %}

templates/apps/proveedores/lista_proveedores.html
{% extends 'base.html' %}
{% block content_main %}
    <h1>Lista de proveedores</h1>
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="{{ object.imagen }}" width="40%" id="imagen_<%= id %>">
                <div class="caption">
                    <h4 class="pull-left">
                        {{ object.get_full_name }}
                    </h4>
                    <h4 class="pull-right">
                        {{ object.tipo }}
                    </h4>

                    <div align="center">
                        <a class="btn blue btn-outline sbold" onclick="" href="{{ object.get_absolute_url }}">
                            Ver productos
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/apps/proveedores/productos_all.html
{% extends 'base.html' %}
{% load humanize staticfiles widget_tweaks %}
{% block content_main %}
    <h3 class="page-title">
        Bienvenido a <strong>Construcosta</strong>
    </h3>

    <div class="row page-bar">
        <div class="col-md-12 text-center">
            <br>
            <h3> filtrar productos por</h3>
        </div>
        {% for field in form %}
            <div class="col-md-4">
                <div class="form-group">{% csrf_token %}
                    <label>{{ field.label }}</label>
                    {% render_field field class='form-control' %}
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="lista-productos">

        </div>
    </div>

{% endblock %}
{% block scripts_js %}

    <script type="text/template" id="productos_item">
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="<%= imagen %>" width="100px" id="imagen_<%= id %>">
                <div class="caption">
                    <h4 class="pull-right">
                        $ <span id="precio__<%= id %>">
                                <%= valor %>
                                </span>
                    </h4>
                    <h4>
                        <a href="#" id="nombre_<%= id %>}">
                            <%= nombre %>
                        </a>
                    </h4>
                    <p id="categoria_{{ producto.id }}">
                        categoria: <strong><%= categoria_nombre %></strong>
                        <br>
                        marca: <strong><%= marca_nombre %></strong>
                    </p>
                    <br>
                    <div align="center">
                        <a class="btn blue btn-outline sbold" onclick="" href="<%= proveedor_url %>">
                            Ver proveedor
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </script>

    <script type="text/javascript">
        window.marca = -1;
        window.categoria = -1;
    </script>

    <script src="{% static 'js/underscore.js' %}"></script>
    <script src="{% static 'js/backbone.js' %}"></script>
    <script src="{% static 'js/backbone/proveedores/models.js' %}"></script>
    <script src="{% static 'js/backbone/proveedores/collections.js' %}"></script>
    <script src="{% static 'js/backbone/proveedores/views.js' %}"></script>
    <script src="{% static 'js/backbone/app.js' %}"></script>

{% endblock %}